package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"go-gin-project/db"
	"go-gin-project/graph/generated"
	"go-gin-project/graph/model"
)

// Mutation
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.CreateTodoInput) (*model.Todo, error) {
	todo := model.Todo{
		UserID: input.UserID,
		Title:  input.Title,
		Done:   false,
	}
	db.DB.Create(&todo)

	return &todo, nil
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, input model.UpdateTodoInput) (*model.Todo, error) {
	todo := model.Todo{}
	if err := db.DB.First(&todo, "id = ?", input.ID).Error; err != nil {
		return nil, err
	}

	todo.Title = input.Title
	todo.Done = input.Done

	db.DB.Save(&todo)

	return &todo, nil
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, input model.DeleteTodoInput) (*model.Todo, error) {
	todo := model.Todo{}
	if err := db.DB.First(&todo, "id = ?", input.ID).Error; err != nil {
		return nil, err
	}

	db.DB.Delete(&todo)

	return &todo, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	user := model.User{
		Name:  input.Name,
		Email: input.Email,
	}
	db.DB.Create(&user)
	return &user, nil
}

// Query
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	todos := []*model.Todo{}
	db.DB.Preload("User").Find(&todos)

	return todos, nil
}

// Todo is the resolver for the todo field.
func (r *queryResolver) Todo(ctx context.Context, input *model.FetchTodoInput) (*model.Todo, error) {
	todo := model.Todo{}

	if err := db.DB.Preload("User").First(&todo, "id = ?", input.ID).Error; err != nil {
		return nil, err
	}

	return &todo, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users := []*model.User{}
	db.DB.Find(&users)

	return users, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, input *model.FetchUserInput) (*model.User, error) {
	user := model.User{}

	if err := db.DB.First(&user, "id = ?", input.ID).Error; err != nil {
		return nil, err
	}

	return &user, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
