// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTodoInput struct {
	Title string `json:"title"`
}

type DeleteTodoInput struct {
	ID int `json:"id"`
}

type FetchTodoInput struct {
	ID int `json:"id"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateTodoInput struct {
	ID    int    `json:"id"`
	Title string `json:"title"`
	Done  bool   `json:"done"`
}
