// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FetchTodo struct {
	ID int `json:"id"`
}

type Mutation struct {
}

type NewTodo struct {
	Title string `json:"title"`
}

type Query struct {
}
